# Generated by Django 4.1.5 on 2023-01-18 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_textinput_delete_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextInput',
        ),
    ]
