# Generated by Django 4.1.5 on 2023-01-19 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FullName',
            new_name='thename',
        ),
    ]
