# Generated by Django 4.1.5 on 2023-01-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_rename_fullname_thename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('exp_date', models.CharField(max_length=7)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='thename',
        ),
    ]
