# Generated by Django 4.1.5 on 2023-01-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_payment_delete_thename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='exp_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='month_pick',
            field=models.CharField(blank=True, choices=[('', 'الشهر'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='year_pick',
            field=models.CharField(blank=True, choices=[('', 'Year'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], max_length=4, null=True),
        ),
    ]
