# Generated by Django 4.1.5 on 2023-01-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_remove_payment_exp_date_payment_month_pick_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='year_pick',
            field=models.CharField(blank=True, choices=[('', 'السنة'), ('23', '2023'), ('24', '2024'), ('25', '2025'), ('26', '2026'), ('27', '2027'), ('28', '2028'), ('29', '2029'), ('30', '2030')], max_length=4, null=True),
        ),
    ]
