# Generated by Django 4.1.5 on 2023-01-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_alter_payment_month_pick_alter_payment_year_pick'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
