# Generated by Django 4.1.5 on 2023-01-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0011_payment_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='full_name',
        ),
        migrations.AddField(
            model_name='payment',
            name='user_ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
