# Generated by Django 4.1.5 on 2023-01-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0012_remove_payment_full_name_payment_user_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='month_pick',
            field=models.CharField(blank=True, choices=[('', 'الشهر'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2),
        ),
        migrations.AlterField(
            model_name='payment',
            name='year_pick',
            field=models.CharField(blank=True, choices=[('', 'السنة'), ('23', '2023'), ('24', '2024'), ('25', '2025'), ('26', '2026'), ('27', '2027'), ('28', '2028'), ('29', '2029'), ('30', '2030')], max_length=4),
        ),
    ]
