# Generated by Django 4.1.5 on 2023-01-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0014_alter_payment_month_pick_alter_payment_year_pick'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
