# Generated by Django 4.1.5 on 2023-01-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0015_payment_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
