# Generated by Django 4.1.5 on 2023-01-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0016_alter_payment_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
