# Generated by Django 4.1.5 on 2023-01-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0017_payment_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='formatted_submission_date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
