# Generated by Django 4.1.5 on 2023-01-24 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0018_payment_formatted_submission_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='formatted_submission_date',
        ),
    ]
