# Generated by Django 4.1.5 on 2023-01-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0019_remove_payment_formatted_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
