# Generated by Django 4.1.5 on 2023-01-27 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0020_payment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='name',
            new_name='full_name',
        ),
    ]
