# Generated by Django 4.1.5 on 2023-01-28 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0022_users_remove_payment_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='playground.payment'),
        ),
    ]
