# Generated by Django 4.1.5 on 2023-01-28 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0024_alter_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='payment',
            new_name='payments',
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='playground.users'),
        ),
    ]
