# Generated by Django 4.1.5 on 2023-01-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0025_rename_payment_users_payments_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
