# Generated by Django 4.1.5 on 2023-02-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0027_payment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
            ],
        ),
    ]
