# Generated by Django 4.1.5 on 2023-02-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0028_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=8),
        ),
    ]
