# Generated by Django 4.1.6 on 2023-02-03 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0029_otp_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.otp')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.users')),
            ],
        ),
    ]
