# Generated by Django 4.1.6 on 2023-02-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0030_paymentdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
