# Generated by Django 4.1.6 on 2023-02-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0031_alter_otp_id_alter_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='user_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
