# Generated by Django 4.1.6 on 2023-02-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0032_payment_full_name_payment_otp_payment_user_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='users',
            name='payments',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED')], default='PENDING', max_length=8),
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.DeleteModel(
            name='PaymentDetails',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
