# Generated by Django 4.1.6 on 2023-02-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0033_remove_paymentdetails_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(max_length=19, null=True),
        ),
    ]
