# Generated by Django 4.1.6 on 2023-02-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0034_alter_payment_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
