# Generated by Django 4.1.6 on 2023-02-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0036_alter_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
