# Generated by Django 4.1.6 on 2023-02-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0038_alter_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
