# Generated by Django 4.1.6 on 2023-02-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0039_blockedip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='blocked',
        ),
    ]
