# Generated by Django 4.1.6 on 2023-02-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0040_remove_payment_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='otp',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
